### ISSUE TITLE
Microsoft Edge support issue

### ISSUE THREAD

**Issue by omartrigui** [medooze/media-server-demo-node#11]
Browser version => 41.16299.371.0
Browser Errors => SCRIPT5022: InvalidAccessError
Demo : /rec

**Comment by murillo128** [comment]
What demo are you trying?

Take note that edge does not support neither simulcast nor vp9 svc...

**Comment by omartrigui** [comment]
I was trying the rec demo using the h264 codec which is already [supported by Edge](https://msdn.microsoft.com/en-us/library/mt599587(v=vs.85).aspx).
