### ISSUE TITLE
Is there any api to run this on multicore CPU

### ISSUE THREAD

**Issue by laowangnj** [medooze/media-server-demo-node#14]
Streamer is suitable for distributing on different servers.

**Comment by murillo128** [comment]
the media server is already multithreaded, so there is no need for such an api.

What are you trying to create or what issue are you having?

**Comment by laowangnj** [comment]
not sure. but "MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 stopped listeners added. Use emitter.setMaxListeners() to increase limit"

**Comment by murillo128** [comment]
That's just a warning, you can safely ignore it

**Comment by laowangnj** [comment]
too many Context Switch.
