### ISSUE TITLE
too many context switch

### ISSUE THREAD

**Issue by laowangnj** [medooze/media-server-demo-node#15]
I've increased about 300 streams out , but too many context switch appear ,about 1k per stream.
Is there any plan to imporve this? otherwise， is this system just for 100 streams ?

**Comment by murillo128** [comment]
What do you mean about to many context switch?

I have run tests up to 1k without issues

**Comment by laowangnj** [comment]
pip install glances
glances
the “ctx_sw”
same code https://github.com/laowangnj/tmpdata.git， but 300 clients

**Comment by murillo128** [comment]
I don't consider the context switching a problem per se.

https://github.com/nicolargo/glances/issues/1212

Too many context switching may increase the cpu time for each concurrent
stream, but it is not a valid metric.

The bottlenecks are cpu usage and network I/O.

I have been able to run up to 700 concurrent clients on a Google Compute
Engine with 8vcpu at 60% cpu usage (higher than that I start to see packet
losses)

We are actively looking for increasing the performance of the media server,
but I don't feel that the context switching is a good metric for monitoring.

**Comment by laowangnj** [comment]
thanks，I'll try again

**Comment by laowangnj** [comment]
run it again.
500 streams out, "top -H -p PID":
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                                                                                                   
24771 root      20   0 28.527g 360324  25248 R 84.8  1.1  10:11.77 ihub                                                                                                                                                                                                      
24770 root      20   0 28.527g 360324  25248 S  9.1  1.1   1:06.53 ihub                                                                                                                                                                                                      
24751 root      20   0 28.527g 360324  25248 S  2.0  1.1   0:15.93 ihub                                                                                                                                                                                                      
25291 root      20   0 28.527g 360324  25248 S  2.0  1.1   0:07.24 ihub                                                                                                                                                                                                      
25308 root      20   0 28.527g 360324  25248 S  2.0  1.1   0:07.26 ihub                                                                                                                                                                                                        
Notice that: One process, as 24771 toke 84.8% cpu usage.

**Comment by murillo128** [comment]
better? worse? :)

**Comment by laowangnj** [comment]
Did it use sha1 only with avx?
"sha1_block_data_order_avx" take most cpu time.

**Comment by murillo128** [comment]
refactored the media-server to use only one thread per endpoint
