### ISSUE TITLE
Why don't  I see any video when I open url https://mylocalip:8000/svc

### ISSUE THREAD

**Issue by garrylea** [medooze/media-server-demo-node#20]
as title, now I successfully have deployed it. but When do I input https://mylocalip:8000/svc in chrome, I don't see any video to show.

I only see two big box "LOCAL" and "REMOTE".  Is this finally result?

**Comment by murillo128** [comment]
please check the javascript console to see any error on the browser. which one are you using?

**Comment by garrylea** [comment]
I get error message "Failed to load resource: the server responded with a status of 404 (Not Found) svc.js:1"  and "Failed to load resource: the server responded with a status of 404 (Not Found) favicon.ico:1 " from javascript console on the browser.

**Comment by murillo128** [comment]
try  https://mylocalip:8000/svc/  (note the / at the end)

**Comment by garrylea** [comment]
Good! Now I can get my video from camera, "/" is very import. thank you.
