### ISSUE TITLE
Best way to stream audio

### ISSUE THREAD

**Issue by tomas-berg** [medooze/media-server-demo-node#22]
What is the best way to stream mp3 file?

**Comment by murillo128** [comment]
convert it to opus and use an mp4 container

**Comment by tomas-berg** [comment]
@murillo128 
thanks

**Comment by tomas-berg** [comment]
@murillo128 
mp4 container can not contain opus codec. Can we use mkv instead?

**Comment by murillo128** [comment]
yes, it does

https://opus-codec.org/docs/opus_in_isobmff.html

only mp4 is supported currently,  sorry

**Comment by tomas-berg** [comment]
It's interesting then how to make it with ffmpeg
`ffmpeg -i input.opus -c:a opus -strict experimental output.mp4`

throws `Could not find tag for codec opus in stream`

**Comment by tomas-berg** [comment]
MP4 doesn't support opus, but MP4v2 does.
Need ffmpeg version 3.4 or above with `-brand mp42` option

**Comment by tomas-berg** [comment]
Got on server side:

> [0x7f08af493740][1543583418.922][LOG]>MP4 opening [./media/output.mp4]
> FindTrackId: Track index doesn't exist - track 0 type hint (../external/mp4v2/lib/src/mp4file.cpp,3002)
> [0x7f08af493740][1543583418.923][LOG]-Found hint track [hintId:0]
> FindTrackIndex: Track id 0 doesn't exist (../external/mp4v2/lib/src/mp4file.cpp,3016)
> FindTrackId: Track index doesn't exist - track 0 type text (../external/mp4v2/lib/src/mp4file.cpp,3002)

ffmpeg file info output:
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'output.mp4':
>   Metadata:
>     major_brand     : mp42
>     minor_version   : 512
>     compatible_brands: isomiso2mp41
>     encoder         : Lavf58.20.100
>   Duration: 00:02:56.35, start: 0.000000, bitrate: 96 kb/s
>     Stream #0:0(und): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 94 kb/s (default)
>     Metadata:
>       handler_name    : SoundHandler
