### ISSUE TITLE
Recorder demo creates unplayable mp4 files

### ISSUE THREAD

**Issue by flaminisx** [medooze/media-server-demo-node#23]
Hi!
I tried to run recording demo and got a problem. Recorder saves 444 bytes videos with no playable tracks.
Can you help me? I can provide any info that you need
Tried on ubuntu and arch

**Comment by jrpedrianes** [comment]
I could record a mp4 file in macos but only using Chrome when I try to record a from firefox or safari I have a mp4 file without tracks

**Comment by murillo128** [comment]
can you try with latest media server?

**Comment by otkelbay** [comment]
I am meeting same problem, ubuntu 16, last media server version.

**Comment by fughur** [comment]
Same here. Using latest version (0.87.0) on win 10 though WSL and node 10.x and latest chrome for client
Also tried older releases (down to 0.80.x) and `ubuntu:bionic`-based docker.

**Comment by murillo128** [comment]
should be fixed now. please test.
