### ISSUE TITLE
Can't install on Mac OS 13.0.1 

### ISSUE THREAD

**Issue by wolf-mik** [medooze/media-server-demo-node#39]
netlink@0.2.4 install /Users/mik/Workspace/media-server/node_modules/netlink
node-gyp-build

CXX(target) Release/obj.target/netlink_binding/src/binding.o
../src/binding.cc:2:10: fatal error: 'linux/netlink.h' file not found
#include <linux/netlink.h>
^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/netlink_binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/Users/xxxxx/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack at ChildProcess.emit (events.js:314:20)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 22.1.0
gyp ERR! command "/Users/mik/.nvm/versions/node/v12.22.12/bin/node" "/Users/mik/.nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mik/Workspace/media-server/node_modules/netlink
gyp ERR! node -v v12.22.12
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

medooze-media-server@0.127.2 install /Users/xxxxxx/Workspace/media-server/node_modules/medooze-media-server
test -f build/Release/medooze-media-server.node || (node-gyp configure && node-gyp rebuild --jobs=max)

CXX(target) Release/obj.target/mp4v2/external/mp4v2/lib/libplatform/io/FileSystem_posix.o
CXX(target) Release/obj.target/mp4v2/external/mp4v2/lib/libplatform/io/FileSystem.o
CXX(target) Release/obj.target/mp4v2/external/mp4v2/lib/libplatform/io/File.o
CXX(target) Release/obj.

**Comment by neilyoung** [comment]
Confirmed. Doesn't work.

**Comment by wolf-mik** [comment]
I have found a way to install it using rosetta and install x64 arch node, it is a work around but it will do the job

**Comment by neilyoung** [comment]
I had a different issue than you ("clang: error: the clang compiler does not support '-march=native'"). Couldn't overcome. Anyway, was just a side activity either, don't bother.

**Comment by wolf-mik** [comment]
Yes I had this too, and I managed to install it using the same way I mentioned earlier you need to convert your arch 
run this in your terminal :
arch -x86_64 /bin/zsh
nvm install <node_version>
  To check which architecture your node installation is targetting, in a shell:

  # Launch the node REPL
  $ node
  > process.arch
  'x64'

if still didn't work then you must make sure that python arch is x86
you need to run the following:
  # Install homebrew
  arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  
  # Install python
  arch -x86_64 /usr/local/bin/brew install python
  ```

  This will install the x86 python binaries under `/usr/local/bin`.

PYTHON=/usr/local/bin/python3 npm ci

**Comment by neilyoung** [comment]
Thanks. But thanks, no. I'm not going to mess it all up just for this. 

But thanks anyway for taking care.
