### ISSUE TITLE
Is it possible to view SDP stream during broadcasting using ffmpeg?

### ISSUE THREAD

**Issue by MaksimDzhangirov** [medooze/media-server-demo-node#4]

**Comment by murillo128** [comment]
Could you explain bit better what is your scenario and what are you trying to do?

**Comment by MaksimDzhangirov** [comment]
Hello. I am trying to create a web application that allows registered users broadcast their webcam video to any other registered user. So usual scenario for a broadcaster is to go on his/her broadcasting page and enable broadcasting. Users, that want to view this broadcast, may go to another page and press "Play" button on some player, that support live video streaming (HLS, DASH, RTMP). Application have to be scalable and support more than 1000 broadcasters and 10000 viewers (in future).
Now I'm searching for media center, that can provide such functionality. I successully run your demo example (on Ubuntu 16.04) and now trying to adopt your 'rec' or 'broadcast' example in such way, that it can be used with FFMPEG ([ffmpeg port to JavaScript](https://github.com/Kagami/ffmpeg.js)) to transcode SDP stream to RTMP.
I also tryed to transcode SDP stream using external FFMPEG version from console but with no success. I created SDP file from SDP answer generated in browser console.
Port 8000 and 5004 are blocked on hosting that I used to run your example, so I use ports 51500 and 51504 to run demo. Can this be an issue?
I am newbie in NodeJs and will be appreciated for any help.

**Comment by murillo128** [comment]
You should be able to use any port with the media server, just let me know which one do you want to change it and I will provide a pointer about were to do it.

You can stream the rtp to an external ffmpeg via the https://medooze.github.io/media-server-node/#streamersession

You can't use the SDP generated by the browser, you will have to manually generate one

**Comment by MaksimDzhangirov** [comment]
I already changed ports in two places - file `index.js` line 111:

    }).listen (51500);

and line 54:

    local  : {
	    port: 51504
    }

Is there another lines in code where I need to change ports?

I don't understand how I can use `StreamerSession` to get RTP stream. Can you provide more information about how to use it or give link to some example?

**Comment by murillo128** [comment]
Check this:

https://github.com/medooze/media-server-node/blob/master/examples/streamer.js

You will have to create one streamer for each media (1 for audio and 1 for video), and attach the streamer output stream to your source input stream and the media server will forward any incoming packet on the source input stream to ffmpeg.

**Comment by MaksimDzhangirov** [comment]
Can I convert `IncomingStreamTrack` to a simple `Buffer`?
I'm tried to use this code, but always get `<Buffer >` as result from console.log(Buffer.from(arr)):

      var rtmpPath = ':44444/live/';
      var fileName = randomstring.generate(20);

      var options=[
              '-fflags', 'nobuffer',                  
	      '-i','-',
	      '-vcodec', 'copy',
	      '-crf', '20',
              '-an',
              '-g', '1', 	                   	                   
              '-probesize', '100000',
	      '-analyzeduration', '0',
	      '-tune', 'zerolatency',
	      '-preset', 'ultrafast',                    
	      '-f', 'flv',
	      'rtmp://localhost' + rtmpPath + fileName
       ];                
       ffmpeg_process=spawn('ffmpeg', options);
       if (ffmpeg_process) {
             try {
                   var videostream = session.getIncomingStreamTrack();
                   toArray(videostream, function (err, arr) {
                             console.log(Buffer.from(arr));
                             ffmpeg_process.stdin.write(Buffer.from(arr));
                   });                            
              } catch (e) {
                     console.info('write error');
              }
         }

**Comment by murillo128** [comment]
no, you can't sorry. You would need to stream the data to ffmpeg via udp

**Comment by MaksimDzhangirov** [comment]
Ok. What I have to modify in this demo to enable UDP streaming?

**Comment by murillo128** [comment]
For example on the recording demo add the following code to create an rtp streamer for video:

```
//Create new streamer
const streamer = MediaServer.createStreamer();

//Create new video session codecs
const video = new MediaInfo("video","video");

//Add h264 codec
video.addCodec(new CodecInfo("h264",96));

//Create session for video
const session = streamer.createSession(video,{
	local  : {
		port: 5004
	},
	remote : {
		ip : "192.168.1.1",
		port: 123456
	}
});
```
And attach the outgoing rtp streamer stream to the incomoing webrtc stream  at
https://github.com/medooze/media-server-demo-node/blob/master/index.js#L504

``` 
//Attach outgoing to incomming
session.getOutgoingStreamTrack().attachTo(incomingStream);
```

**Comment by MaksimDzhangirov** [comment]
I added this part to index.js:

    case "ffmpeg-to-rtmp":
	{
		const connection = request.accept(protocol);

		connection.on('message', (frame) =>
		{
			console.log('in FFMPEG part');
			//Get cmd
			var msg = JSON.parse(frame.utf8Data);
			
			//Get cmd
			if (msg.cmd==="OFFER")
			{
		
				//Process the sdp
				var offer = SDPInfo.process(msg.offer);										
				
				//Create an DTLS ICE transport in that enpoint
				const transport = endpoint.createTransport({
					dtls : offer.getDTLS(),
					ice  : offer.getICE() 
				});

				//Set RTP remote properties
				transport.setRemoteProperties({
					audio : offer.getMedia("audio"),
					video : offer.getMedia("video")
				});

				//Get local DTLS and ICE info
				const dtls = transport.getLocalDTLSInfo();
				const ice  = transport.getLocalICEInfo();

				//Get local candidates
				const candidates = endpoint.getLocalCandidates();

				//Create local SDP info
				let answer = new SDPInfo();
				
				//Add ice and dtls info
				answer.setDTLS(dtls);
				answer.setICE(ice);
				//For each local candidate
				for (let i=0;i<candidates.length;++i)
					//Add candidate to media info
					answer.addCandidate(candidates[i]);
				
				//Get remote video m-line info 
				let audioOffer = offer.getMedia("audio");

				//If offer had audio
				if (audioOffer)
				{
					//Create audio media
					let  audio = new MediaInfo(audioOffer.getId(), "audio");
					//Get codec types
					let opus = audioOffer.getCodec("opus");
					//Add audio codecs
					audio.addCodec(opus);
					//Set recv only
					audio.setDirection(Direction.RECVONLY);						
					//Add it to answer
					answer.addMedia(audio);
				}

				//Get remote video m-line info 
				let videoOffer = offer.getMedia("video");

				//If offer had video
				if (videoOffer)
				{
					//Create video media
					let video = new MediaInfo(videoOffer.getId(), "video");
					
					//Get codec types
					let h264 = videoOffer.getCodec("h264");
					//Add video codecs
					video.addCodec(h264);
					//Limit incoming bitrate
					//video.setBitrate(1024);

					//Add video extensions
					for (let [id, uri] of videoOffer.getExtensions().entries())
						//Add it
						video.addExtension(id, uri);

					//Add it to answer
					answer.addMedia(video);
				}

				//Set RTP local  properties
				transport.setLocalProperties({
					audio : answer.getMedia("audio"),
					video : answer.getMedia("video")
				});

				//For each stream offered
				for (let offered of offer.getStreams().values())
				{
					//Create the remote stream into the transport
					const incomingStream = transport.createIncomingStream(offered);

					//Create new local stream with only audio
					const outgoingStream  = transport.createOutgoingStream({
						audio: false,
						video: true
					});

					//Get local stream info
					const info = outgoingStream.getStreamInfo();

					//Copy incoming data from the remote stream to the local one
					outgoingStream.attachTo(incomingStream);

					//Add local stream info it to the answer
					answer.addStream(info);									

				}
				const newStreamer = MediaServer.createStreamer();
				//Create new video session codecs
				const newVideoSession = new MediaInfo("video","video");

				//Add h264 codec
				newVideoSession.addCodec(new CodecInfo("h264", 96));
				const newPort = 52300;
				const newSession = newStreamer.createSession(newVideoSession, {
					local  : {
						port: newPort
					},
					remote : {
						ip : ip,
						port: newPort+2
					}
				});
				const newIncomingStream = newSession.getIncomingStreamTrack();
				newSession.getOutgoingStreamTrack().attachTo(newIncomingStream);
                                //Send response
				connection.sendUTF(JSON.stringify({
					type: "answer",
					answer : answer.toString()
				}));
				
				//Close on disconnect
				connection.on("close",() => {
					//Stop session
					newSession.stop();
                                        newStreamer.stop();
					// stop ffmpeg
					killFfmpegProcess();
					transport.stop();
				});
			}	
		});
		break;
	}

How I can check that UDP stream is working?

**Comment by murillo128** [comment]
tcpdump
