### ISSUE TITLE
[question] does media-server support chrome's style  simalcast

### ISSUE THREAD

**Issue by notedit** [medooze/media-server-demo-node#6]
i see your example using  RtpSender's setParameters,  for chrome we can only modify the sdp to support simalcast, so does media-server support chrome's style simalcast sdp format?

**Comment by murillo128** [comment]
Yes, see https://github.com/medooze/semantic-sdp-js/blob/master/test/simulcast_sim.js

**Comment by murillo128** [comment]
I mean, media server supports it, but it is not implemented on the demo client-side yet
